[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
startup_mode = "Maximized"
dynamic_padding = false

[window.padding]
x = 5
y = 5

[font]
size = 15

[font.bold]
family = "Monaco Nerd Font"

[font.bold_italic]
family = "Monaco Nerd Font"

[font.italic]
family = "Monaco Nerd Font"

[font.normal]
family = "Monaco Nerd Font"

[colors.primary]
background = "0x1f1f1f"
foreground = "0xcccccc"

[colors.cursor]
text = "#181818"
cursor = "#cccccc"

[colors.normal]
black = "0x1f1f1f"
red = "0xf44747"
green = "0x6a9955"
yellow = "0xd7ba7d"
blue = "0x569cd6"
magenta = "0xc586c0"
cyan = "0x4dc9b0"
white = "0xdddddd"

[colors.bright]
black = "0x808080"
red = "0xf55757"
green = "0x80ad6b"
yellow = "0xe1cb9e"
blue = "0x6fabdc"
magenta = "0xd6a9d2"
cyan = "0x70d3bf"
white = "0xffffff"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "V", mods = "Command", action = "Paste" },
{ key = "C", mods = "Command", action = "Copy" },
{ key = "Plus", mods = "Command", action = "IncreaseFontSize" },
{ key = "Minus", mods = "Command", action = "DecreaseFontSize" },
{ key = "Key0", mods = "Command", action = "ResetFontSize" },
{ key = "F", mods = "Command|Control", action = "ToggleFullscreen" },
{ key = "Tab", mods = "Control", action = "SelectNextTab" },
{ key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" }
]

[scrolling]
history = 10000
multiplier = 3
[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "open"
post_processing = true
mouse.enabled = true
binding = { key = "U", mods = "Command" }

[general]
live_config_reload = true
